// Catapult v3 four-lane 10.3125 Gbit/s transceiver validation.
//
// The Arria 10 Native PHY serial-loopback input returns each transmitter to
// its corresponding receiver inside the FPGA PMA.  The physical RX pins are
// not used by the checker, and this result cannot validate the retimer, cage,
// module, cable, or any remote endpoint.
//
// Safety invariant: the fPLL and transceiver reset controller can
// leave reset only while the active-low QSFP module-present input reports that
// no module is installed.  Inserting a module while this image is running
// powers the PLL path down again.

module qsfp_internal_loopback (
    input  wire       clk_u59,
    input  wire       clk_y5,
    input  wire       modprsl,
    input  wire [3:0] qsfp_rx,
    output wire [3:0] qsfp_tx
);

    localparam integer LANES = 4;

    reg [7:0] por_count;
    reg       modprsl_meta;
    reg       modprsl_sync;
    reg [31:0] heartbeat;

    wire [7:0] control_source;
    wire test_requested = control_source[0];
    wire clear_requested = control_source[1];
    wire reset_requested = control_source[2];
    wire por_done = &por_count;
    wire safe_enable = por_done && modprsl_sync && test_requested;

    always @(posedge clk_u59) begin
        if (!por_done)
            por_count <= por_count + 1'b1;
        modprsl_meta <= modprsl;
        modprsl_sync <= modprsl_meta;
        heartbeat <= heartbeat + 1'b1;
    end

    // Y5 directly clocks the receiver CDRs and an fPLL in Transceiver mode.
    // The fPLL's MCGB distributes its 5.15625 GHz serial clock over the xN
    // non-bonded clock network to all four 10.3125 Gbit/s transmitters.
    wire fpll_locked;
    wire fpll_cal_busy;
    wire fpll_mcgb_serial_clk;
    wire fpll_tx_serial_clk_unused;
    wire [0:0] fpll_powerdown;
    wire reset_request = !safe_enable || reset_requested;

    fpll tx_fpll (
        .mcgb_rst(reset_request),
        .mcgb_serial_clk(fpll_mcgb_serial_clk),
        .pll_cal_busy(fpll_cal_busy),
        .pll_locked(fpll_locked),
        .pll_powerdown(fpll_powerdown[0]),
        .pll_refclk0(clk_y5),
        .tx_serial_clk(fpll_tx_serial_clk_unused)
    );

    wire [3:0] tx_analogreset;
    wire [3:0] tx_digitalreset;
    wire [3:0] rx_analogreset;
    wire [3:0] rx_digitalreset;
    wire [3:0] tx_ready;
    wire [3:0] rx_ready;
    wire [3:0] tx_cal_busy;
    wire [3:0] rx_cal_busy;
    wire [3:0] rx_is_lockedtodata;
    wire [3:0] rx_is_lockedtoref;
    wire [3:0] tx_cal_busy_combined =
        tx_cal_busy | {LANES{fpll_cal_busy}};

    xcvr_reset_controller reset_controller (
        .clock(clk_u59),
        .pll_cal_busy(fpll_cal_busy),
        .pll_locked(fpll_locked),
        .pll_powerdown(fpll_powerdown),
        .pll_select(1'b0),
        .reset(reset_request),
        .rx_analogreset(rx_analogreset),
        .rx_cal_busy(rx_cal_busy),
        .rx_digitalreset(rx_digitalreset),
        .rx_is_lockedtodata(rx_is_lockedtodata),
        .rx_ready(rx_ready),
        .tx_analogreset(tx_analogreset),
        .tx_cal_busy(tx_cal_busy_combined),
        .tx_digitalreset(tx_digitalreset),
        .tx_ready(tx_ready)
    );

    wire [3:0] tx_pma_clkout_unused;
    wire [3:0] tx_pma_div_clkout;
    wire [3:0] rx_pma_div_clkout;
    wire [3:0] tx_clkout_unused;
    wire [3:0] rx_clkout_unused;
    wire [3:0] tx_serial_clk = {LANES{fpll_mcgb_serial_clk}};
    // Keep every non-bonded lane in its own parallel-clock domain.  This is
    // the connection topology generated by Intel's Native PHY example rules
    // when the /33 PMA divider ports are enabled.
    wire [3:0] tx_coreclkin = tx_pma_div_clkout;
    wire [3:0] rx_coreclkin = rx_pma_div_clkout;

    reg [31:0] tx_block_count [0:LANES-1];
    reg [3:0]  tx_enable_meta;
    reg [3:0]  tx_enable_sync;
    reg [3:0]  tx_ready_meta;
    reg [3:0]  tx_ready_sync;
    reg [3:0]  inject_meta;
    reg [3:0]  inject_sync;
    wire [255:0] tx_parallel_data;

    genvar lane;
    generate
        for (lane = 0; lane < LANES; lane = lane + 1) begin : lane_transmit
            always @(posedge tx_pma_div_clkout[lane]) begin
                tx_enable_meta[lane] <= safe_enable;
                tx_enable_sync[lane] <= tx_enable_meta[lane];
                tx_ready_meta[lane] <= tx_ready[lane];
                tx_ready_sync[lane] <= tx_ready_meta[lane];
                inject_meta[lane] <= control_source[3 + lane];
                inject_sync[lane] <= inject_meta[lane];
                if (!tx_ready_sync[lane])
                    tx_block_count[lane] <= 32'd0;
                else if (tx_enable_sync[lane])
                    tx_block_count[lane] <= tx_block_count[lane] + 1'b1;
            end

            assign tx_parallel_data[(64*lane) +: 64] = {
                (32'h4c503100 + lane),
                tx_block_count[lane] ^ {31'd0, inject_sync[lane]}
            };
        end
    endgenerate

    // Bit 64 is tx_control[2*lane], bit 65 is tx_control[2*lane+1].
    // 2'b01 is therefore the legal 64b/66b data-block sync header.
    wire [7:0] tx_control = 8'h55;
    wire [3:0] tx_enh_data_valid = tx_ready_sync & tx_enable_sync;

    wire [255:0] rx_parallel_data;
    wire [7:0]   rx_control;
    wire [3:0]   rx_enh_blk_lock;
    wire [3:0]   rx_enh_fifo_empty;
    wire [3:0]   rx_enh_fifo_full;
    wire [3:0]   rx_enh_fifo_pempty;
    wire [3:0]   rx_enh_fifo_pfull;
    wire [3:0]   rx_enh_fifo_rd_en;

    xcvr_superlite_ii native_phy (
        .rx_analogreset(rx_analogreset),
        .rx_cal_busy(rx_cal_busy),
        .rx_cdr_refclk0(clk_y5),
        .rx_clkout(rx_clkout_unused),
        .rx_control(rx_control),
        .rx_coreclkin(rx_coreclkin),
        .rx_digitalreset(rx_digitalreset),
        .rx_enh_blk_lock(rx_enh_blk_lock),
        .rx_enh_fifo_empty(rx_enh_fifo_empty),
        .rx_enh_fifo_full(rx_enh_fifo_full),
        .rx_enh_fifo_pempty(rx_enh_fifo_pempty),
        .rx_enh_fifo_pfull(rx_enh_fifo_pfull),
        .rx_enh_fifo_rd_en(rx_enh_fifo_rd_en),
        .rx_is_lockedtodata(rx_is_lockedtodata),
        .rx_is_lockedtoref(rx_is_lockedtoref),
        .rx_parallel_data(rx_parallel_data),
        .rx_pma_div_clkout(rx_pma_div_clkout),
        .rx_serial_data(qsfp_rx),
        .rx_seriallpbken(4'hf),
        .rx_set_locktodata(4'h0),
        .rx_set_locktoref(4'h0),
        .tx_analogreset(tx_analogreset),
        .tx_cal_busy(tx_cal_busy),
        .tx_clkout(tx_clkout_unused),
        .tx_control(tx_control),
        .tx_coreclkin(tx_coreclkin),
        .tx_digitalreset(tx_digitalreset),
        .tx_enh_data_valid(tx_enh_data_valid),
        .tx_parallel_data(tx_parallel_data),
        .tx_pma_clkout(tx_pma_clkout_unused),
        .tx_pma_div_clkout(tx_pma_div_clkout),
        .tx_serial_clk0(tx_serial_clk),
        .tx_serial_data(qsfp_tx),
        .unused_rx_control(),
        .unused_rx_parallel_data(),
        .unused_tx_control(64'd0),
        .unused_tx_parallel_data(256'd0)
    );

    // Every accepted received data block must advance by one.  Acquisition is
    // deliberately per lane: this proves all four independent PMA/PCS paths,
    // while making no claim about a multi-lane external protocol or deskew.
    reg [3:0]  read_valid_d;
    reg [3:0]  checker_acquired;
    reg [3:0]  lock_seen;
    reg [3:0]  fifo_overflow_sticky;
    reg [31:0] rx_block_count [0:LANES-1];
    reg [31:0] rx_error_count [0:LANES-1];
    reg [15:0] rx_lock_loss_count [0:LANES-1];
    reg [31:0] rx_last_count [0:LANES-1];
    reg [3:0]  clear_meta_rx;
    reg [3:0]  clear_sync_rx;
    reg [3:0]  blk_lock_meta_rx;
    reg [3:0]  blk_lock_sync_rx;
    reg [3:0]  ready_meta_rx;
    reg [3:0]  ready_sync_rx;
    reg [3:0]  fifo_full_meta_rx;
    reg [3:0]  fifo_full_sync_rx;
    reg [3:0]  fifo_pempty_rx;
    reg [3:0]  fifo_rd_en_rx;
    assign rx_enh_fifo_rd_en = fifo_rd_en_rx;

    generate
        for (lane = 0; lane < LANES; lane = lane + 1) begin : lane_checker
            wire [63:0] lane_data = rx_parallel_data[(64*lane) +: 64];
            wire [1:0] lane_header = rx_control[(2*lane) +: 2];
            wire [31:0] lane_signature = 32'h4c503100 + lane;

            always @(posedge rx_pma_div_clkout[lane]) begin
                clear_meta_rx[lane] <= clear_requested;
                clear_sync_rx[lane] <= clear_meta_rx[lane];
                blk_lock_meta_rx[lane] <= rx_enh_blk_lock[lane];
                blk_lock_sync_rx[lane] <= blk_lock_meta_rx[lane];
                ready_meta_rx[lane] <= rx_ready[lane];
                ready_sync_rx[lane] <= ready_meta_rx[lane];
                fifo_full_meta_rx[lane] <= rx_enh_fifo_full[lane];
                fifo_full_sync_rx[lane] <= fifo_full_meta_rx[lane];
                fifo_pempty_rx[lane] <= rx_enh_fifo_pempty[lane];
                fifo_rd_en_rx[lane] <= ready_sync_rx[lane] &&
                    blk_lock_sync_rx[lane] && !fifo_pempty_rx[lane];
                read_valid_d[lane] <= fifo_rd_en_rx[lane];

                if (clear_sync_rx[lane]) begin
                    rx_block_count[lane] <= 32'd0;
                    rx_error_count[lane] <= 32'd0;
                    rx_lock_loss_count[lane] <= 16'd0;
                    rx_last_count[lane] <= 32'd0;
                    checker_acquired[lane] <= 1'b0;
                    lock_seen[lane] <= 1'b0;
                    fifo_overflow_sticky[lane] <= 1'b0;
                end else begin
                    if (fifo_full_sync_rx[lane])
                        fifo_overflow_sticky[lane] <= 1'b1;

                    if (blk_lock_sync_rx[lane]) begin
                        lock_seen[lane] <= 1'b1;
                    end else begin
                        if (lock_seen[lane])
                            rx_lock_loss_count[lane] <=
                                rx_lock_loss_count[lane] + 1'b1;
                        lock_seen[lane] <= 1'b0;
                        checker_acquired[lane] <= 1'b0;
                    end

                    if (!ready_sync_rx[lane]) begin
                        fifo_rd_en_rx[lane] <= 1'b0;
                        read_valid_d[lane] <= 1'b0;
                        checker_acquired[lane] <= 1'b0;
                    end else if (read_valid_d[lane]) begin
                        rx_block_count[lane] <=
                            rx_block_count[lane] + 1'b1;
                        if (lane_header != 2'b01 ||
                                lane_data[63:32] != lane_signature) begin
                            rx_error_count[lane] <=
                                rx_error_count[lane] + 1'b1;
                            checker_acquired[lane] <= 1'b0;
                        end else if (!checker_acquired[lane]) begin
                            rx_last_count[lane] <= lane_data[31:0];
                            checker_acquired[lane] <= 1'b1;
                        end else begin
                            if (lane_data[31:0] !=
                                    (rx_last_count[lane] + 1'b1))
                                rx_error_count[lane] <=
                                    rx_error_count[lane] + 1'b1;
                            rx_last_count[lane] <= lane_data[31:0];
                        end
                    end
                end
            end
        end
    endgenerate

    // On-die temperature capture; the conversion used by the host script is
    // T(C) = 693 * code / 1024 - 265, matching the working PCIe demo.
    wire [9:0] temp_raw_wire;
    wire       temp_eoc;
    reg        temp_eoc_meta;
    reg        temp_eoc_sync;
    reg        temp_eoc_prev;
    reg [9:0]  temp_code;
    reg        temp_valid;

    altera_temp_sense temp_sensor (
        .corectl(1'b1),
        .reset(1'b0),
        .eoc(temp_eoc),
        .tempout(temp_raw_wire)
    );

    always @(posedge clk_u59) begin
        temp_eoc_meta <= temp_eoc;
        temp_eoc_sync <= temp_eoc_meta;
        temp_eoc_prev <= temp_eoc_sync;
        if (temp_eoc_prev && !temp_eoc_sync) begin
            temp_code <= temp_raw_wire;
            temp_valid <= 1'b1;
        end
    end

    // Cross clock-domain counters as Gray code so every ISSP snapshot is a
    // coherent old or new value.  Status bits use explicit two-flop sampling.
    wire [31:0] heartbeat_gray = heartbeat ^ (heartbeat >> 1);
    wire [31:0] tx_count_gray =
        tx_block_count[0] ^ (tx_block_count[0] >> 1);
    wire [31:0] rx_block_gray [0:LANES-1];
    wire [31:0] rx_error_gray [0:LANES-1];
    wire [15:0] rx_lock_loss_gray [0:LANES-1];

    generate
        for (lane = 0; lane < LANES; lane = lane + 1) begin : gray_encode
            assign rx_block_gray[lane] =
                rx_block_count[lane] ^ (rx_block_count[lane] >> 1);
            assign rx_error_gray[lane] =
                rx_error_count[lane] ^ (rx_error_count[lane] >> 1);
            assign rx_lock_loss_gray[lane] =
                rx_lock_loss_count[lane] ^ (rx_lock_loss_count[lane] >> 1);
        end
    endgenerate

    reg [55:0] status_meta;
    reg [55:0] status_sync;
    wire [55:0] status_async = {
        fifo_overflow_sticky,
        checker_acquired,
        rx_cal_busy,
        tx_cal_busy,
        rx_enh_fifo_pempty,
        rx_enh_fifo_empty,
        rx_enh_fifo_pfull,
        rx_enh_fifo_full,
        rx_enh_blk_lock,
        rx_is_lockedtoref,
        rx_is_lockedtodata,
        rx_ready,
        tx_ready,
        fpll_cal_busy,
        fpll_locked,
        fpll_cal_busy,
        fpll_locked
    };
    reg [31:0] tx_gray_meta;
    reg [31:0] tx_gray_sync;
    reg [31:0] block_gray_meta [0:LANES-1];
    reg [31:0] block_gray_sync [0:LANES-1];
    reg [31:0] error_gray_meta [0:LANES-1];
    reg [31:0] error_gray_sync [0:LANES-1];
    reg [15:0] loss_gray_meta [0:LANES-1];
    reg [15:0] loss_gray_sync [0:LANES-1];
    integer sync_lane;

    always @(posedge clk_u59) begin
        status_meta <= status_async;
        status_sync <= status_meta;
        tx_gray_meta <= tx_count_gray;
        tx_gray_sync <= tx_gray_meta;
        for (sync_lane = 0; sync_lane < LANES; sync_lane = sync_lane + 1) begin
            block_gray_meta[sync_lane] <= rx_block_gray[sync_lane];
            block_gray_sync[sync_lane] <= block_gray_meta[sync_lane];
            error_gray_meta[sync_lane] <= rx_error_gray[sync_lane];
            error_gray_sync[sync_lane] <= error_gray_meta[sync_lane];
            loss_gray_meta[sync_lane] <= rx_lock_loss_gray[sync_lane];
            loss_gray_sync[sync_lane] <= loss_gray_meta[sync_lane];
        end
    end

    wire [478:0] probe_data;
    assign probe_data[0] = modprsl_sync;
    assign probe_data[1] = safe_enable;
    assign probe_data[57:2] = status_sync;
    assign probe_data[58] = temp_valid;
    assign probe_data[68:59] = temp_code;
    assign probe_data[76:69] = control_source;
    assign probe_data[108:77] = heartbeat_gray;
    assign probe_data[140:109] = tx_gray_sync;
    assign probe_data[172:141] = block_gray_sync[0];
    assign probe_data[204:173] = error_gray_sync[0];
    assign probe_data[220:205] = loss_gray_sync[0];
    assign probe_data[252:221] = block_gray_sync[1];
    assign probe_data[284:253] = error_gray_sync[1];
    assign probe_data[300:285] = loss_gray_sync[1];
    assign probe_data[332:301] = block_gray_sync[2];
    assign probe_data[364:333] = error_gray_sync[2];
    assign probe_data[380:365] = loss_gray_sync[2];
    assign probe_data[412:381] = block_gray_sync[3];
    assign probe_data[444:413] = error_gray_sync[3];
    assign probe_data[460:445] = loss_gray_sync[3];
    assign probe_data[461] = fpll_powerdown[0];
    assign probe_data[462] = reset_request;
    assign probe_data[466:463] = tx_analogreset;
    assign probe_data[470:467] = tx_digitalreset;
    assign probe_data[474:471] = rx_analogreset;
    assign probe_data[478:475] = rx_digitalreset;

    altsource_probe #(
        .sld_auto_instance_index("YES"),
        .sld_instance_index(0),
        .instance_id("QSL1"),
        .probe_width(479),
        .source_width(8),
        .source_initial_value("0"),
        .enable_metastability("YES")
    ) loopback_probe (
        .probe(probe_data),
        .source(control_source),
        .source_clk(clk_u59),
        .source_ena(1'b1)
    );

    initial begin
        por_count = 0;
        modprsl_meta = 0;
        modprsl_sync = 0;
        heartbeat = 0;
        tx_block_count[0] = 0;
        tx_block_count[1] = 0;
        tx_block_count[2] = 0;
        tx_block_count[3] = 0;
        tx_enable_meta = 0;
        tx_enable_sync = 0;
        tx_ready_meta = 0;
        tx_ready_sync = 0;
        inject_meta = 0;
        inject_sync = 0;
        read_valid_d = 0;
        checker_acquired = 0;
        lock_seen = 0;
        fifo_overflow_sticky = 0;
        clear_meta_rx = 0;
        clear_sync_rx = 0;
        blk_lock_meta_rx = 0;
        blk_lock_sync_rx = 0;
        ready_meta_rx = 0;
        ready_sync_rx = 0;
        fifo_full_meta_rx = 0;
        fifo_full_sync_rx = 0;
        fifo_pempty_rx = 4'hf;
        fifo_rd_en_rx = 0;
        temp_eoc_meta = 0;
        temp_eoc_sync = 0;
        temp_eoc_prev = 0;
        temp_code = 0;
        temp_valid = 0;
        status_meta = 0;
        status_sync = 0;
        tx_gray_meta = 0;
        tx_gray_sync = 0;
        for (sync_lane = 0; sync_lane < LANES; sync_lane = sync_lane + 1) begin
            rx_block_count[sync_lane] = 0;
            rx_error_count[sync_lane] = 0;
            rx_lock_loss_count[sync_lane] = 0;
            rx_last_count[sync_lane] = 0;
            block_gray_meta[sync_lane] = 0;
            block_gray_sync[sync_lane] = 0;
            error_gray_meta[sync_lane] = 0;
            error_gray_sync[sync_lane] = 0;
            loss_gray_meta[sync_lane] = 0;
            loss_gray_sync[sync_lane] = 0;
        end
    end

endmodule
